import { AppDataSource } from "../../config/DataSource.js";
import { PostReviewModel } from "../../domain/entities/PostReviewModel.js";
import { IPostReviewRepository } from "../../domain/interface_repositories/IPostReview_repository.js";
import { PostReviewEntity, PostReviewType } from "../entities/PostReviewEntity.js";
import { BasePostEntity } from "../entities/PostEntities/BasePostEntity.js";
import { UserEntity } from "../entities/UserEntity.js";
import { EntityManager, In } from "typeorm";

export class PostReviewRepositoryImpl implements IPostReviewRepository {
  
    private postReviewDataSource = AppDataSource.getRepository(PostReviewEntity);

    public toDomainPostReview(reviewEntity: PostReviewEntity): PostReviewModel {
        return new PostReviewModel({
            reviewId: reviewEntity.reviewId,
            rating: reviewEntity.rating,
            comment: reviewEntity.comment,
            reviewType: reviewEntity.reviewType,
            createdAt: reviewEntity.createdAt,
            reviewerUserId: reviewEntity.reviewer.userId,
            postId: reviewEntity.post.postId
        });
    }

    public toEntityPostReview(postReviewModel: PostReviewModel): PostReviewEntity {
        const reviewType = postReviewModel.reviewType === 'PRODUCT_RATING' ? PostReviewType.PROMOTION_RATING : PostReviewType.RECRUIT_RATING; // Adjust as needed
        const reviewEntity: PostReviewEntity = this.postReviewDataSource.create({
            // On creation, reviewId is generated by the database, so we don't set it.
            rating: postReviewModel.rating,
            comment: postReviewModel.comment,
            reviewType: reviewType,
            createdAt: postReviewModel.createdAt || new Date(),
            reviewer: { userId: postReviewModel.reviewerUserId } as UserEntity,
            post: { postId: postReviewModel.postId } as BasePostEntity,
        });
        return reviewEntity;
    }

    async addPostReview(review: PostReviewModel): Promise<PostReviewModel> {
        const entity = this.toEntityPostReview(review);
        const savedEntity = await this.postReviewDataSource.save({
            ...entity,
            post: { postId: review.postId },
            reviewer: { userId: review.reviewerUserId }
        });
        const newReview = await this.postReviewDataSource.findOne({
                where: { reviewId: savedEntity.reviewId },
                relations: ['reviewer', 'post']
            });
        return this.toDomainPostReview(newReview);
    }

    async getPostReviewByPostId(postId: string): Promise<PostReviewModel> {
        const review = await this.postReviewDataSource.findOne({
            where: { post: { postId: postId } },
            relations: ['reviewer', 'post']
        });

        return review ? this.toDomainPostReview(review) : null;
    }
    async getReviewByPostReviewId(reviewId: string): Promise<PostReviewModel> {
        const review = await this.postReviewDataSource.findOne({
            where: { reviewId: reviewId },
            relations: ['reviewer', 'post']
        });
        if (!review) throw new Error("Review not found");

        return this.toDomainPostReview(review);
    }
    async getApplyPostReviewsByPostIds(postIds: string[], manager?: EntityManager): Promise<PostReviewModel[]> {
        const postReviewRepo = manager ? manager.getRepository(PostReviewEntity) : this.postReviewDataSource;
        const reviews = await postReviewRepo.find({
            where: { post: {postId: In(postIds)} },
            relations: {
                post: true,
                reviewer: true
            }
        });
        return reviews.map((review) => this.toDomainPostReview(review));
    }
}